[project]
name = "enfys-ltm-tester"
version = "0.1.0"
description = "Simple python script to test the LTM protocol on the Enfys device."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pyserial>=3.5"]
